name: Build and Release Docs

on: [push]

jobs:

  build-release-docs:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: eu-west-2
      BUCKET_NAME: diffusion-model-framework
    permissions:
      id-token: write   # This is required for requesting the JWT
      contents: read    # This is required for actions/checkout
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up python
        id: setup-python
        uses: actions/setup-python@v5
        with:
          python-version: "^3.9.0"
      #----------------------------------------------
      #  -----  install & configure poetry  -----
      #----------------------------------------------
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
      #----------------------------------------------
      # install dependencies if cache does not exist
      #----------------------------------------------
      - name: Install dependencies
        run: poetry install --only documentation

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1.7.0
        with:
          role-to-assume: arn:aws:iam::980416368045:role/GitHubAction-AssumeRoleWithAction
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{ env.AWS_REGION }}
      - name: Build and Deploy docs
        run: |
          poetry run sphinx-build -M html docs/source/ docs/build

          aws s3 sync docs/build/html s3://${{ env.BUCKET_NAME }}/pages/v$(poetry version) --delete
          aws s3 sync docs/build/html s3://${{ env.BUCKET_NAME }}/latest --delete

          rm -rf docs/build
